---
  - name: Create security group for squid proxy
    ec2_group:
      name:             "{{ aws_squid_sec_group_name }}"
      description:      "{{ aws_squid_sec_group_name }}"
      vpc_id:           "{{ vpc_id }}"
      region:           "{{ aws_region }}"
      rules:
        - proto:        "tcp"
          from_port:    "3128"
          to_port:      "3128"
          cidr_ip:      "{{ vpc_cidr_block }}"
        - proto:        "tcp"
          from_port:    "22"
          to_port:      "22"
          cidr_ip:      "0.0.0.0/0"
      tags:
        Name: "{{ aws_squid_sec_group_name }}"
        KubernetesCluster: "{{ kubernetes_cluster_tag_value }}"
    register: squid_sec_group

  - name: Create EC2 instance for squid proxy
    ec2:
      key_name: "{{ ssh_key_name }}"
      instance_type: "{{ proxy_instance_type }}"
      instance_tags:
        Name: "{{ proxy_instance_name }}"
      image: "{{ aws_ami_id }}"
      wait: yes
      exact_count: 1
      count_tag:
        Name: "{{ proxy_instance_name }}"
      group_id: "{{ squid_sec_group.group_id }}"
      vpc_subnet_id: "{{ public_subnet_a_id }}"
      assign_public_ip: yes
      region: "{{ aws_region }}"
    register: proxy_ec2_instance

  - name: Record squid proxy IP addresses
    set_fact:
      proxy_public_ip: "{{ proxy_ec2_instance.tagged_instances[0].public_ip }}"
      proxy_private_ip: "{{ proxy_ec2_instance.tagged_instances[0].private_ip }}"

  - name: Wait for SSH to come up on squid proxy instance {{ proxy_public_ip }}
    wait_for:
      host: "{{ proxy_public_ip }}"
      port: 22
      delay: 0
      timeout: 320
      state: started
