reset_cluster: False

openshift_clients:
  '3.6':
    url: https://github.com/openshift/origin/releases/download/v3.6.0
    release_ver: openshift-origin-client-tools-v3.6.0-c4dd4cf
  '3.7':
    url: https://github.com/openshift/origin/releases/download/v3.7.0-alpha.1
    release_ver: openshift-origin-client-tools-v3.7.0-alpha.1-fdbd3dc
  latest:
    url: https://apb-oc.s3.amazonaws.com/apb-oc
    release_ver: oc

openshift_client_version: 'latest'
oc_tools_dir: /usr/local/bin

# Temporary fix until release version of oc client works with latest images.
openshift_client_url: https://s3.amazonaws.com/catasb/linux/amd64/oc
