---

  - name: Create ext4 filesystems for /var/lib/docker, /tmp, persistent volumes
    async: 200
    register: filesystem_creations
    poll: 0
    filesystem:
      fstype: ext4
      dev: '{{ item }}'
      opts: -E lazy_itable_init
    with_items:
      - "{{ var_lib_docker_block_device }}"
      - "{{ tmp_block_device }}"
      - "{{ persistent_vol_block_device }}"

  - name: Wait for ext4 filesystems to finish creating
    async_status: jid={{ item.ansible_job_id }}
    register: result
    until: result.finished
    retries: 20
    delay: 10
    with_items: '{{ filesystem_creations.results }}'

  - name: Mount /var/lib/docker
    mount:
      name: "{{ var_lib_docker_mount_point }}"
      src:  "{{ var_lib_docker_block_device }}"
      fstype: ext4
      state: mounted

  - name: Mount /tmp
    mount:
      name: "{{ tmp_mount_point }}"
      src:  "{{ tmp_block_device }}"
      fstype: ext4
      state: mounted

  - name: Adjust permissions of /tmp
    file:
      path: /tmp
      owner: root
      group: root
      mode: 01777
      state: directory

  - name: Restorecon /tmp
    shell: restorecon -R /tmp

  - name: Mount persistent volumes filesystem
    mount:
      name: "{{ persistent_vol_mount_point }}"
      src:  "{{ persistent_vol_block_device }}"
      fstype: ext4
      state: mounted
