# TODO: Don't use this file! It's fallen well behind upstream, and this needs
# to get updated to reflect the latest permissions
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ olm_osb_catalog_name }}"
  namespace: "{{ olm_namespace }}"
data:
  customResourceDefinitions: |-
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: templateservicebrokers.osb.openshift.io
      spec:
        group: osb.openshift.io
        names:
          kind: TemplateServiceBroker
          listKind: TemplateServiceBrokerList
          plural: templateservicebrokers
          singular: templateservicebroker
        scope: Namespaced
        version: v1alpha1
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: ansibleservicebrokers.osb.openshift.io
      spec:
        group: osb.openshift.io
        names:
          kind: AnsibleServiceBroker
          listKind: AnsibleServiceBrokerList
          plural: ansibleservicebrokers
          singular: ansibleservicebroker
        scope: Namespaced
        version: v1alpha1
  clusterServiceVersions: |-
    - apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: templateservicebrokeroperator.v0.1.0
        namespace: placeholder
      spec:
        displayName: Template Service Broker Operator
        description: Template Service Broker Operator
        keywords: ['template', 'broker', 'open service broker']
        version: 0.1.0
        maturity: alpha
        maintainers:
        - name: Red Hat, Inc.
          email: ansible-service-broker@redhat.com
        provider:
          name: Red Hat, Inc.
        labels:
          alm-status-descriptors: templateservicebrokeroperator.v0.1.0
          operated-by: templateservicebrokeroperator
        selector:
          matchLabels:
            operated-by: templateservicebrokeroperator
        install:
          strategy: deployment
          spec:
            permissions:
            - serviceAccountName: template-service-broker-operator
              rules:
              - apiGroups:
                - osb.openshift.io
                resources:
                - "*"
                verbs:
                - "*"
              - apiGroups:
                - ""
                resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                verbs:
                - "*"
              - apiGroups:
                - apps
                resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
                verbs:
                - "*"
            deployments:
            - name: template-service-broker-operator
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    name: template-service-broker-operator-alm-owned
                template:
                  metadata:
                    name: template-service-broker-operator-alm-owned
                    labels:
                      name: template-service-broker-operator-alm-owned
                  spec:
                    serviceAccountName: template-service-broker-operator
                    containers:
                    - name: template-service-broker-operator
                      image: "{{ olm_tsb_full_image }}"
                      imagePullPolicy: IfNotPresent
        customresourcedefinitions:
          owned:
          - name: templateservicebrokers.osb.openshift.io
            version: v1alpha1
            kind: TemplateServiceBroker
            displayName: Template Service Broker
            description: An Open Service Broker supporting management of OpenShift templates.
    - apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: ansibleservicebrokeroperator.v0.1.0
        namespace: placeholder
      spec:
        displayName: Ansible Service Broker Operator
        description: Ansible Service Broker Operator
        keywords: ['Ansible', 'broker', 'open service broker']
        version: 0.1.0
        maturity: alpha
        maintainers:
        - name: Red Hat, Inc.
          email: ansible-service-broker@redhat.com
        provider:
          name: Red Hat, Inc.
        labels:
          alm-status-descriptors: ansibleservicebrokeroperator.v0.1.0
          operated-by: ansibleservicebrokeroperator
        selector:
          matchLabels:
            operated-by: ansibleservicebrokeroperator
        install:
          strategy: deployment
          spec:
            permissions:
            - serviceAccountName: ansible-service-broker-operator
              rules:
              - apiGroups:
                - osb.openshift.io
                resources:
                - "*"
                verbs:
                - "*"
              - apiGroups:
                - ""
                resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                verbs:
                - "*"
              - apiGroups:
                - apps
                resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
                verbs:
                - "*"
            deployments:
            - name: ansible-service-broker-operator
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    name: ansible-service-broker-operator-alm-owned
                template:
                  metadata:
                    name: ansible-service-broker-operator-alm-owned
                    labels:
                      name: ansible-service-broker-operator-alm-owned
                  spec:
                    serviceAccountName: ansible-service-broker-operator
                    containers:
                    - name: ansible-service-broker-operator
                      image: "{{ olm_asb_full_image }}"
                      imagePullPolicy: IfNotPresent
        customresourcedefinitions:
          owned:
          - name: ansibleservicebrokers.osb.openshift.io
            version: v1alpha1
            kind: AnsibleServiceBroker
            displayName: Ansible Service Broker
            description: An Open Service Broker supporting management of Ansible Playbooks.
  packages: |-
    - packageName: templateservicebroker
      channels:
      - name: alpha
        currentCSV: templateservicebrokeroperator.v0.1.0
    - packageName: ansibleservicebroker
      channels:
      - name: alpha
        currentCSV: ansibleservicebrokeroperator.v0.1.0
