---
- set_fact:
    msg: |
        EC-2 Instance Tags:        Name={{ instance_name }}
        EC-2 Instance ID:          {{ my_ec2_instances.tagged_instances[0].id }}
        Associated to Elastic IP:  {{ elastic_ip.public_ip }}
        Hostname:                  {{ aws_custom_prefix }}.{{ target_dns_zone }}
        SSH Key Name:              {{ ssh_key_name }}
        Region:                    {{ aws_region }}
  when: not post_openshift_install

- set_fact:
    msg: | 
        EC-2 Instance Tags:        Name={{ instance_name }}
        Hostname:                  {{ openshift_hostname }}
        OpenShift URL:             {{ openshift_url }}
        SSH Key Name:              {{ ssh_key_name }}
        Region:                    {{ aws_region }}
        Next steps:
        1) Visit https://apiserver-service-catalog.{{ openshift_routing_suffix }}
        2) Accept the certificate
        3) Visit https://{{ openshift_hostname }}:8443 for the console
        4) Provision a RDS APB into awsdemo project
        5) Add to the aws-demo project a Python 3.5 project based off of https://github.com/thesteve0/awsdemo.git
        6) Click on the python project and select creating binding to the RDS APB
        7) Redeploy the python project
        OR
        For CLI access:
        oc login --insecure-skip-tls-verify {{ openshift_hostname }}:8443 -u {{ cluster_user }} -p {{ cluster_user_password }}
  when: post_openshift_install

- debug:
    msg: "{{ msg.split('\n') }}"
