- hosts: localhost
  gather_facts: True
  tasks:
    - name: EC2 Remote Facts
      ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ instance_name }}"
        region: "{{ aws_region }}"
      register: my_ec2_facts
  post_tasks:
    - set_fact:
        msg: |
            EC-2 Instance Tags:        Name={{ instance_name }}
            Hostname:                  {{ openshift_hostname }}
            OpenShift URL:             {{ openshift_url }}
            SSH Key Name:              {{ ssh_key_name }}
            Region:                    {{ aws_region }}
            Next steps:
            1) Visit https://apiserver-service-catalog.{{ openshift_hostname }}
            2) Accept the certificate
            3) Visit https://{{ openshift_hostname }}:8443 for the console
            4) Provision a RDS APB into awsdemo project
            5) Add to the aws-demo project a Python 3.5 project based off of https://github.com/thesteve0/awsdemo.git
            6) Click on the python project and select creating binding to the RDS APB
            7) Redeploy the python project
            OR
            For CLI access:
            oc login --insecure-skip-tls-verify {{ openshift_hostname }}:8443 -u {{ cluster_user }} -p {{ cluster_user_password }}
    - debug:
        msg: "{{ msg.split('\n') }}"
