- hosts: localhost
  gather_facts: True
  vars_prompt:
    - name: dockerhub_user_name
      prompt: "Enter your dockerhub username: "
      private: no
    - name: dockerhub_user_password
      prompt: "Enter your dockerhub password: "
      private: yes
    - name: dockerhub_org_name
      prompt: "Enter the dockerhub organization you'd like to pull images from: "
      private: no
  roles:
    - { role: openshift_setup, reset_cluster: True }
    - service_catalog_setup
    - ansible_service_broker_setup
    - local_demo_prep
    - env_hacks
  post_tasks:
    - set_fact:
        msg: |
            Hostname:                  {{ openshift_hostname }}
            Next steps:
            1) Visit https://apiserver-service-catalog.{{ openshift_routing_suffix }}
            2) Accept the certificate
            3) Visit https://{{ openshift_hostname }}:8443 for the console
            OR
            For CLI access:
            oc login --insecure-skip-tls-verify {{ openshift_hostname }}:8443 -u {{ cluster_user }} -p {{ cluster_user_password }}
    - debug:
        msg: "{{ msg.split('\n') }}"
