- hosts: localhost
  gather_facts: True
  vars:
    broker_ci: False
  vars_prompt:
    - name: dockerhub_org
      prompt: "Enter the dockerhub organization you'd like to pull images from"
      private: no
  roles:
    - { role: awsservicebroker_prep, when: deploy_awsservicebroker == True}
    - "{{ cluster }}_setup"
    - { role: ansible_service_broker_setup, when: (not broker_ci) and (deploy_asb == True)}
    - { role: awsservicebroker_setup, when: (not broker_ci) and (deploy_awsservicebroker == True)}
    - { role: olm_setup, when: deploy_olm == True}
  post_tasks:
    - set_fact:
        msg: |
            Hostname:                  {{ hostname }}
            Web: https://{{ hostname }}:8443
            CLI: oc login --insecure-skip-tls-verify {{ hostname }}:8443 -u {{ cluster_user }} -p {{ cluster_user_password }}
      when: cluster == 'openshift'
    - set_fact:
        msg: |
            Hostname:                  {{ hostname }}
            Kubernetes Cluster is running at http://{{ hostname }}:6443
      when: cluster == 'kubernetes'
    - debug:
        msg: "{{ msg.split('\n') }}"
